# Basic settings
replicaCount: 1
image:
  repository: bitnami/kafka
  tag: latest

# Kafka configuration
kafka:
  topicPartitions: 3
  replicationFactor: 1
  topics:
    - bookings
  consumerGroups:
    - booking-processor-group

# ZooKeeper configuration
zookeeper:
  enabled: false
externalZookeeper:
  servers:
    - zookeeper