apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 2181