apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  labels:
    app: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: booking:latest  # assuming image is built locally in minikube
          imagePullPolicy: Never
          ports:
            - containerPort: 8080