apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: your-registry/booking:latest
          ports:
            - containerPort: 8080