apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-processor
  template:
    metadata:
      labels:
        app: booking-processor
    spec:
      containers:
        - name: booking-processor
          image: your-registry/booking-processor:latest
          ports:
            - containerPort: 8080