apiVersion: v1
kind: Service
metadata:
  name: booking-processor
  labels:
    app: booking-processor
spec:
  type: ClusterIP
  selector:
    app: booking-processor
  ports:
    - port: 8080
      targetPort: 8080